### ISSUE TITLE
Make the topic root path configurable

### ISSUE THREAD

**Issue by bluewalk** [githubcdr/opentherm2mqtt#1]
Hi, first off, nice job!

Do you think it's possible to make the topic root path configurable and starting with the same root topic, eg otgw/control , otgw/log , otgw/value and otgw/status? This way it would make it easier to implement it into an already existing broker.

Also, just a minor thing tho, leading forward slashes are not common practice.

Cheers

**Comment by githubcdr** [comment]
Good feedback I missed, sorry :)

I agree the starting slash was silly and I removed this. I like your suggestion, for now I use

control/<device>/
value/<device>/
log/<device>/
status/<device>/

I feel this is more scalable for other devices, also I implemented a mqtt will in /status.

This is the best option for me at the moment but feel free to change as you like ofcourse.
